---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= replace this
    volumes:
    #replace the following with your own directories
      - /home/berry/homeserver/plex/config:/config 
      - /home/berry/homeserver/plex/TV:/tv
      - /home/berry/homeserver/plex/movies:/movies
    restart: unless-stopped
